import Head from "next/head";
import { Accordion } from "@components/Accordion";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rebecca Friedman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Accordion title="Rebecca Friedman" icon={<div>?</div>}>
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
        </Accordion>
        <Accordion title="Rebecca Friedman" icon={<div>?</div>}>
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
        </Accordion>
        <Accordion title="Rebecca Friedman" icon={<div>?</div>}>
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
          Rebecca Friedman is an artist and designer based in Portland, Oregon.
        </Accordion>
      </main>
    </>
  );
}
