import Head from "next/head";
import { Accordion } from "@components/Accordion";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rebecca Friedman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Accordion
          title="Project Title"
          subTitle="project subtitle"
          icon={<div>?</div>}
          description={
            <>
              Rebecca Friedman is an artist and designer based in Portland,
              Oregon. Rebecca Friedman is an artist and designer based in
              Portland, Oregon. Rebecca Friedman is an artist and designer based
            </>
          }
        >
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
        </Accordion>
        <Accordion
          title="Project Title"
          subTitle="project subtitle"
          icon={<div>?</div>}
          description={
            <>
              Rebecca Friedman is an artist and designer based in Portland,
              Oregon. Rebecca Friedman is an artist and designer based in
              Portland, Oregon. Rebecca Friedman is an artist and designer based
              in Portland, Oregon. Rebecca Friedman is an artist and designer
              based in Portland, Oregon. Rebecca Friedman is an artist and
              designer based in Portland, Oregon. Rebecca Friedman is an artist
              and designer based in Portland, Oregon. Rebecca Friedman is an
              artist and designer based in Portland, Oregon. Rebecca Friedman is
              an artist and designer based in Portland, Oregon.
            </>
          }
        >
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
        </Accordion>
        <Accordion
          title="Project Title"
          subTitle="project subtitle"
          icon={<div>?</div>}
          description={
            <>
              Rebecca Friedman is an artist and designer based in Portland,
              Oregon. Rebecca Friedman is an artist and designer based in
            </>
          }
        >
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
          <img src="http://placekitten.com/200/300" />
        </Accordion>
      </main>
    </>
  );
}
